# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AttachmentManager
                                 A QGIS plugin
 This plugin provides functionality that makes it possible to add, delete and show attachments (files) to geographic objects in a PostGIS database.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-07
        copyright            : (C) 2025 by Morten Storm, Styrke 10 ApS
        email                : morten@styrke10.dk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AttachmentManager class from file AttachmentManager.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .attachmentmanager import AttachmentManager
    return AttachmentManager(iface)
