# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AttachmentManager
                                 A QGIS plugin
 This plugin provides functionality that makes it possible to add, delete and show attachments (files) to geographic objects in a PostGIS database.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-07
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Morten Storm, Styrke 10 ApS
        email                : morten@styrke10.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import Qt, QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.core import Qgis, QgsMessageLog, QgsProject
import re

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .attachmentmanager_dialog import AttachmentManagerDialog
import os.path


class AttachmentManager:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'AttachmentManager_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&AttachmentManager')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
        # Prepare attribute for temporary folder name
        self.tempFolder = None
        # Attribute for connection parameters
        self.connParams = None
        
        self.dlgActive = False    

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('AttachmentManager', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/attachmentmanager/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'AttachmentManager'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True
        self.lastActiveLayer = None
            
        # Detect changes in active layer
        self.iface.currentLayerChanged.connect(self.onActiveLayerChanged)
        

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&AttachmentManager'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""
        QgsMessageLog.logMessage("Calling run()", tag="AttachmentManager", level=Qgis.Info )

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = AttachmentManagerDialog(parent=self.iface.mainWindow(),plugin=self)
            # Set window flags to stay on top of QGIS only
            self.dlg.setWindowFlags(Qt.Dialog)

        # Get active layer
        activeLayer = self.iface.activeLayer()
        QgsMessageLog.logMessage(f"Active layer: '{activeLayer.name()}'", tag="AttachmentManager", level=Qgis.Info )

        # Check if active layer is selected
        if activeLayer != None:
            connectionParams = self.getConnParams(activeLayer)
            
            # show the dialog
            self.dlg.show()
            self.dlgActive = True
            # Run the dialog event loop
            result = self.dlg.exec_()
            # See if OK was pressed
            if result:
                # Do something useful here - delete the line containing pass and
                # substitute with your code.
                pass
        else:
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Icon.Warning)
            msgBox.setWindowTitle("Advarsel")
            msgBox.setText("Der er ikke valgt et aktivt lag!\n\nVælg venligst et lag, og prøv igen!")
            msgBox.setStandardButtons(QMessageBox.StandardButton.Ok)
            msgBox.exec()

    def fillAttachmentList(self, layer):
        self.connParams = self.getConnParams(layer)
        self.loadAttachmentList(layer)
        QgsMessageLog.logMessage(f"Connection params: '{self.connParams}'", tag="AttachmentManager", level=Qgis.Info )
        

    def getConnParams(self, activeLayer):
        QgsMessageLog.logMessage(f"Active layer source: '{activeLayer.source()}'", tag="AttachmentManager", level=Qgis.Info )
        if activeLayer.dataProvider().name() != 'postgres':
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Icon.Warning)
            msgBox.setWindowTitle("Advarsel")
            msgBox.setText("Kun PostGIS lag er understøttet!\n\nVælg venligst et andet lag, og prøv igen!")
            msgBox.setStandardButtons(QMessageBox.StandardButton.Ok)
            msgBox.exec()
            return None

        # Return connection parameters as a dictionary
        return parseConnectionString(activeLayer.source())
            

    def onActiveLayerChanged(self, layer):
        if layer and self.dlgActive: 
            if self.lastActiveLayer and layer.id() != self.lastActiveLayer:
                QgsMessageLog.logMessage(f"Layer changed: '{layer.name()} id: {layer.id()}'", tag="AttachmentManager", level=Qgis.Info )
                layer.selectionChanged.connect(onSelectionChanged)

                self.lastActiveLayer = layer.id()
        else:
            # Check if the layer panel contains layers at all
            if len(QgsProject.instance().mapLayers()) > 0:
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Icon.Warning)
                msgBox.setWindowTitle("Advarsel")
                msgBox.setText("Der er ikke valgt et aktivt lag!\n\nVælg venligst et lag, og prøv igen!")
                msgBox.setStandardButtons(QMessageBox.StandardButton.Ok)
                msgBox.exec()
    
    def loadAttachmentList(self, layer):
        pass
        
    def onSelectionChanged(self):
        QgsMessageLog.logMessage(f"Selection changed - number of selected features: '{self.activeLayer.selectedFeatures()}'", tag="AttachmentManager", level=Qgis.Info )


def parseConnectionString(s):
    pattern = re.compile(r'(\w+)=(".*?"|\'.*?\'|\S+)')
    matches = pattern.findall(s)
    return {key: value.strip('\'"') for key, value in matches}
