# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AttachmentManagerDialog
                                 A QGIS plugin
 This plugin provides functionality that makes it possible to add, delete and show attachments (files) to geographic objects in a PostGIS database.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-07
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Morten Storm, Styrke 10 ApS
        email                : morten@styrke10.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import tempfile
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import Qgis, QgsMessageLog


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'attachmentmanager_dialog_base.ui'))


class AttachmentManagerDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None, plugin=None):
        """Constructor."""
        super(AttachmentManagerDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        
        self.setupUi(self)
        self.plugin = plugin
        
        # Connect the close button to the function doing this
        self.btnClose.clicked.connect(self.closeDlg)
        
        # Create temporary folder for files being previewed
        self.plugin.tempFolder = tempfile.TemporaryDirectory()
        QgsMessageLog.logMessage(f"Temp folder set to: '{self.plugin.tempFolder}'", tag="AttachmentManager", level=Qgis.Info )


    def closeDlg(self):
        # Close the dialog
        self.close()

    def closeEvent(self, event):
        # Clean up temporary folder
        QgsMessageLog.logMessage("Temp folder cleaning coming up!", tag="AttachmentManager", level=Qgis.Info )
        self.plugin.tempFolder.cleanup()
        self.plugin.dlgActive = False
        
        super().closeEvent(event)
