# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AttachmentManager
                                 A QGIS plugin
 This plugin provides functionality that makes it possible to add, delete and show attachments (files) to geographic objects in a PostGIS database.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-07
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Morten Storm, Styrke 10 ApS
        email                : morten@styrke10.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# ---------------------------------------------------------------------------
# Qt5 / Qt6 compatibility shim
# ---------------------------------------------------------------------------
# QGIS 3.x ships Qt5; QGIS 4.x ships Qt6.  Both expose the same public API
# through qgis.PyQt, but a few things changed between versions:
#
#   * WindowModality, AlignmentFlag, etc. moved from Qt.* to Qt.<Enum>.* in Qt6.
#   * exec_() was deprecated in Qt6 in favour of exec() – qgis.PyQt keeps exec_()
#     as an alias, but we prefer exec() going forward.
#   * QFileDialog.ExistingFile moved to QFileDialog.FileMode.ExistingFile in Qt6
#     (QGIS's qgis.PyQt already exposes the new path, but we guard both).
#   * QMessageBox.Yes / .No moved to QMessageBox.StandardButton.Yes / .No –
#     the code already uses StandardButton.* throughout, so no change needed.
#   * QAction, QDesktopServices, QIcon etc. are unchanged.
#
# The shim detects the Qt major version once at import time and defines
# stable aliases that the rest of the module uses.
# ---------------------------------------------------------------------------
try:
    # qVersion() returns Qt's own runtime version string (e.g. "5.15.3" or "6.5.2").
    # Using it is more reliable than PYQT_VERSION_STR, which reflects the PyQt
    # binding version and can differ from the underlying Qt major version.
    from qgis.PyQt.QtCore import qVersion as _qVersion  # type: ignore
    _QT_MAJOR = int(_qVersion().split(".")[0])
except Exception:
    _QT_MAJOR = 5  # safe fallback

from qgis.PyQt.QtCore import (  # type: ignore
    Qt, QSettings, QTranslator, QCoreApplication, QUrl
)
from qgis.PyQt.QtGui import QIcon, QDesktopServices  # type: ignore
from qgis.PyQt.QtWidgets import (  # type: ignore
    QAction, QMessageBox, QFileDialog, QApplication
)
from qgis.core import Qgis, QgsMessageLog  # type: ignore

import sys
import psycopg2
import os
import uuid
import tempfile
import atexit
import configparser
from psycopg2 import Binary

# ---------------------------------------------------------------------------
# Stable aliases for enum values that moved between Qt5 and Qt6
# ---------------------------------------------------------------------------

# Qt enum values moved into typed sub-enums in Qt6.
# Pattern: Qt.<EnumType>.<Value> (Qt6) with Qt.<Value> fallback (Qt5).

try:
    _DialogFlag = Qt.WindowType.Dialog           # Qt6
except AttributeError:
    _DialogFlag = Qt.Dialog                      # Qt5

try:
    _UniqueConnection = Qt.ConnectionType.UniqueConnection  # Qt6
except AttributeError:
    _UniqueConnection = Qt.UniqueConnection                 # Qt5

# QFileDialog.ExistingFile
try:
    _ExistingFile = QFileDialog.FileMode.ExistingFile   # Qt6 / newer PyQt5 builds
except AttributeError:
    _ExistingFile = QFileDialog.ExistingFile            # older PyQt5

# Initialize Qt resources from file resources.py
from .resources import *  # noqa: F401,F403
# Import the code for the dialog
from .attachmentmanager_dialog import AttachmentManagerDialog
import os.path


class AttachmentManager:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor."""
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        # Load locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir, 'i18n',
            'attachmentmanager_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)
            QgsMessageLog.logMessage(
                f"Locale set to: '{locale}'", tag="AttachmentManager", level=Qgis.Info)
        else:
            QgsMessageLog.logMessage(
                f"Locale file not found for: '{locale}'", tag="AttachmentManager", level=Qgis.Info)

        self.actions = []
        self.menu = self.tr(u'&AttachmentManager')
        self.first_start = None

        # Temporary folder for previewed files
        self.tempFolder = tempfile.TemporaryDirectory()
        QgsMessageLog.logMessage(
            f"Temp folder set to: '{self.tempFolder}'", tag="AttachmentManager", level=Qgis.Info)

        self._cleanedTempDir = False
        QApplication.instance().aboutToQuit.connect(self._cleanup_temp_dir)
        atexit.register(self._cleanup_temp_dir)

        self.connParams = None
        self.dlgActive = False
        self.relationalID = None
        self.selectedFeatureID = None

        self.readConfig()

    def tr(self, message):
        """Qt translation helper (we do not inherit QObject)."""
        translation = QCoreApplication.translate('AttachmentManager', message)
        QgsMessageLog.logMessage(
            f"Translating message: '{message}' -> '{translation}'",
            tag="AttachmentManager", level=Qgis.Info)
        return translation

    def add_action(self, icon_path, text, callback, enabled_flag=True,
                   add_to_menu=True, add_to_toolbar=True,
                   status_tip=None, whats_this=None, parent=None):
        """Add a toolbar icon to the toolbar."""
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)
        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = ':/plugins/attachmentmanager/attachment.png'
        self.add_action(
            icon_path,
            text=self.tr(u'AttachmentManager'),
            callback=self.run,
            parent=self.iface.mainWindow())
        self.first_start = True
        self.lastActiveLayer = None
        self.iface.currentLayerChanged.connect(self.onActiveLayerChanged)

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        self._cleanup_temp_dir()
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&AttachmentManager'), action)
            self.iface.removeToolBarIcon(action)

    def _cleanup_temp_dir(self):
        """Safely cleanup the temporary directory (idempotent)."""
        if self._cleanedTempDir:
            return
        try:
            self.tempFolder.cleanup()
            self._cleanedTempDir = True
            QgsMessageLog.logMessage(
                f"Temp folder deleted: {self.tempFolder.name}",
                "AttachmentManager", level=Qgis.Info)
        except Exception as e:
            try:
                import shutil
                shutil.rmtree(self.tempFolder, ignore_errors=True)
                self._cleanedTempDir = True
                QgsMessageLog.logMessage(
                    f"Temp folder force-removed (fallback): {self.tempFolder.name}",
                    "AttachmentManager", level=Qgis.Warning)
            except Exception as e2:
                QgsMessageLog.logMessage(
                    f"Failed to delete temp folder: {e} / Fallback error: {e2}",
                    "AttachmentManager", level=Qgis.Critical)

    def readConfig(self):
        """Read settings from ini file."""
        config = configparser.ConfigParser()
        config.read("AttachmentManager.ini")
        self.tablePostfix = config.get("AttachmentSetup", "tablepostfix", fallback="_Attachments")
        self.fieldPrefix = config.get("AttachmentSetup", "fieldprefix", fallback="rel")
        self.fieldSetup = {
            'id_field':      config.get("TableSetup", "id_field",      fallback="Id"),
            'name_field':    config.get("TableSetup", "name_field",    fallback="FileName"),
            'content_field': config.get("TableSetup", "content_field", fallback="FileContent"),
        }

    def run(self):
        """Run method that performs all the real work."""
        QgsMessageLog.logMessage("Calling run()", tag="AttachmentManager", level=Qgis.Info)

        if self.first_start == True:
            self.first_start = False
            self.dlg = AttachmentManagerDialog(parent=self.iface.mainWindow(), plugin=self)
            self.dlg.setWindowFlags(_DialogFlag)
            self.dlg.btnAttachShow.clicked.connect(self.showAttachment)
            self.dlg.btnAttachAdd.clicked.connect(self.addAttachment)
            self.dlg.btnAttachDelete.clicked.connect(self.deleteAttachment)
            self.dlg.listAttachment.doubleClicked.connect(self.showAttachment)

        activeLayer = self.iface.activeLayer()
        if activeLayer:
            QgsMessageLog.logMessage(
                f"Active layer: '{activeLayer.name()}'", tag="AttachmentManager", level=Qgis.Info)
        else:
            QgsMessageLog.logMessage("No active layer", tag="AttachmentManager", level=Qgis.Info)

        if self.lastActiveLayer and \
                self.lastActiveLayer.receivers(self.lastActiveLayer.selectionChanged) > 0:
            self.lastActiveLayer.selectionChanged.disconnect(self.onSelectionChanged)

        if activeLayer is not None:
            if self.checkLayerOrigin(activeLayer):
                self.layerHasAttachments = self.checkLayerAttachmentTable(activeLayer)
                self.lastActiveLayer = activeLayer
                text = self.tr("Attachments on the selected feature on layer")
                self.dlg.attachmentLabel.setText(f"{text} '{activeLayer.name()}'")
                activeLayer.selectionChanged.connect(
                    self.onSelectionChanged, type=_UniqueConnection)
            self.dlg.show()
            self.dlgActive = True
            # exec() is the cross-version call; qgis.PyQt aliases exec_() for Qt5 compat
            result = self.dlg.exec()
            if result:
                pass
        elif self.dlgActive:
            self.dlg.attachmentLabel.setText(self.tr("No active layer selected"))
            showMsgBox(
                self.tr("You have not selected an active layer!\n\nPlease select a layer and try again!"),
                title=self.tr("Warning"), icon=QMessageBox.Icon.Warning)

    def onActiveLayerChanged(self, layer):
        QgsMessageLog.logMessage(
            f"Active layer changing! {layer.name() if layer else 'None'}",
            tag="AttachmentManager", level=Qgis.Info)
        if layer and self.dlgActive:
            if layer != self.lastActiveLayer:
                if self.checkLayerOrigin(layer):
                    self.layerHasAttachments = self.checkLayerAttachmentTable(layer)
                    if self.layerHasAttachments:
                        if self.lastActiveLayer:
                            self.lastActiveLayer.selectionChanged.disconnect(self.onSelectionChanged)
                        layer.selectionChanged.connect(
                            self.onSelectionChanged, type=_UniqueConnection)
                        self.lastActiveLayer = layer
                        text = self.tr("Attachments on the selected feature on layer")
                        self.dlg.attachmentLabel.setText(f"{text} '{layer.name()}'")
                else:
                    self.dlg.listAttachment.clear()

    def checkLayerOrigin(self, layer):
        QgsMessageLog.logMessage(
            f"Checking layer origin! '{layer.name()}'", tag="AttachmentManager", level=Qgis.Info)
        if layer.dataProvider().name() != 'postgres':
            self.dlg.attachmentLabel.setText(self.tr("Active layer is not a PostGIS layer"))
            showMsgBox(
                self.tr("The selected layer is not a PostGIS layer!"),
                title=self.tr("Warning"), icon=QMessageBox.Icon.Warning)
            self.connParams = None
            return False
        self.connParams = parseConnectionString(layer.source())
        QgsMessageLog.logMessage(
            f"PostGIS lag -> Connection params: '{self.connParams}'",
            tag="AttachmentManager", level=Qgis.Info)
        return True

    def checkLayerAttachmentTable(self, layer):
        QgsMessageLog.logMessage(
            f"Connecting to '{self.connParams['dbname']}' table '{self.connParams['table'][1]}'"
            f" on '{self.connParams['host']}'", 'AttachmentManager', level=Qgis.Info)
        attTable = self.connParams['table'][1] + self.tablePostfix
        connection = psycopg2.connect(
            database=self.connParams['dbname'], user=self.connParams['user'],
            host=self.connParams['host'], password=self.connParams['password'])
        cursor = connection.cursor()
        sql = (f"SELECT table_name FROM information_schema.tables "
               f"WHERE table_schema = '{self.connParams['table'][0]}' "
               f"AND table_type = 'BASE TABLE' AND table_name = '{attTable}';")
        QgsMessageLog.logMessage(f"SQL statement: '{sql}'", 'AttachmentManager', level=Qgis.Info)
        cursor.execute(sql)
        row = cursor.fetchone()

        if row is not None:
            QgsMessageLog.logMessage(
                f"Attachment table '{attTable}' exists!", 'AttachmentManager', level=Qgis.Info)
            text = self.tr("Attachments on the selected feature on layer")
            self.dlg.attachmentLabel.setText((f"{text} '{layer.name()}'"))
            self.findRelationalID(cursor, attTable, self.connParams['table'][0])
            self.loadAttachmentList(layer)
            connection.close()
            self.dlg.btnSetupAttachments.setEnabled(False)
            return True
        else:
            QgsMessageLog.logMessage(
                f"No attachment table on layer '{layer.name()}'", 'AttachmentManager', level=Qgis.Info)
            text = self.tr("No attachments on layer")
            self.dlg.attachmentLabel.setText(f"{text} '{layer.name()}'")
            self.dlg.listAttachment.clear()
            text1 = self.tr("The selected layer has no associated attachment table\n(")
            text2 = self.tr("is missing)!\n\nCreate an attachment table or select another layer!")
            showMsgBox(f"{text1}'{attTable}'{text2}",
                title=self.tr("Warning"), icon=QMessageBox.Icon.Warning)
            connection.close()
            self.dlg.btnSetupAttachments.setEnabled(True)
            return False

    def findRelationalID(self, cursor, attTable, schema):
        cursor.execute(f'SELECT * FROM "{schema}"."{attTable}" LIMIT 0')
        columns = [desc[0] for desc in cursor.description]
        self.relationalID = None
        for col in columns:
            if col.split('_')[0] == self.fieldPrefix:
                self.relationalID = col
                break

    def loadAttachmentList(self, layer):
        QgsMessageLog.logMessage(
            f"Clearing and loading attachment from new selection: {layer.name()}",
            tag="AttachmentManager", level=Qgis.Info)
        attTable = self.connParams['table'][1] + self.tablePostfix
        schema = self.connParams['table'][0]
        self.dlg.listAttachment.clear()

        selectedFeatures = layer.selectedFeatures()
        if len(selectedFeatures) != 1:
            return
        self.selectedFeatureID = selectedFeatures[0].id()

        connection = psycopg2.connect(
            database=self.connParams['dbname'], user=self.connParams['user'],
            host=self.connParams['host'], password=self.connParams['password'])
        cursor = connection.cursor()
        sql = (f'SELECT "{self.fieldSetup["name_field"]}" FROM "{schema}"."{attTable}" '
               f'WHERE "{self.relationalID}" = {self.selectedFeatureID};')
        QgsMessageLog.logMessage(f"SQL statement: '{sql}'", 'AttachmentManager', level=Qgis.Info)
        cursor.execute(sql)
        rows = cursor.fetchall()
        for row in rows:
            self.dlg.listAttachment.addItem(row[0])
        if self.dlg.listAttachment.count() > 0:
            self.dlg.listAttachment.setCurrentRow(0)
        connection.close()

    def onSelectionChanged(self, selected_ids, deselected_ids, clear_and_select):
        if not selected_ids and not deselected_ids:
            return
        QgsMessageLog.logMessage(
            f"Selection changed - number of selected features: {self.lastActiveLayer.selectedFeatureCount()}",
            tag="AttachmentManager", level=Qgis.Info)
        if self.dlgActive:
            if self.lastActiveLayer.selectedFeatureCount() != 1:
                showMsgBox(
                    self.tr("Select exactly one feature to view attachments!"),
                    title=self.tr("Warning"), icon=QMessageBox.Icon.Warning)
                self.dlg.listAttachment.clear()
            else:
                QgsMessageLog.logMessage(
                    "Exactly 1 feature selected!", tag="AttachmentManager", level=Qgis.Info)
                self.loadAttachmentList(self.lastActiveLayer)

    def showAttachment(self):
        QgsMessageLog.logMessage("Show attachment called!", tag="AttachmentManager", level=Qgis.Info)
        item = self.dlg.listAttachment.currentItem()
        if item is None:
            showMsgBox(self.tr("No attachment selected in the list!"),
                       title=self.tr("Warning"), icon=QMessageBox.Icon.Warning)
            return

        connection = psycopg2.connect(
            database=self.connParams['dbname'], user=self.connParams['user'],
            host=self.connParams['host'], password=self.connParams['password'])
        cursor = connection.cursor()

        attTable = self.connParams['table'][1] + self.tablePostfix
        schema = self.connParams['table'][0]
        sql = (f'SELECT "{self.fieldSetup["content_field"]}" FROM "{schema}"."{attTable}" '
               f'WHERE "{self.relationalID}" = {self.selectedFeatureID} '
               f'AND "{self.fieldSetup["name_field"]}" = \'{item.text()}\';')
        QgsMessageLog.logMessage(f"SQL statement: '{sql}'", 'AttachmentManager', level=Qgis.Info)
        cursor.execute(sql)
        row = cursor.fetchone()

        if row is None:
            showMsgBox(self.tr("Could not find the selected attachment in the database!"),
                       title=self.tr("Error"), icon=QMessageBox.Icon.Critical)
            connection.close()
            return

        fileContent = row[0]
        if fileContent is None or len(fileContent) == 0:
            showMsgBox(self.tr("The selected attachment is empty!"),
                       title=self.tr("Error"), icon=QMessageBox.Icon.Critical)
            connection.close()
            return

        if isinstance(fileContent, memoryview):
            fileContent = fileContent.tobytes()

        if not isinstance(fileContent, (bytes, bytearray)):
            showMsgBox(self.tr("Attachment content is not valid"),
                       title=self.tr("Error"), icon=QMessageBox.Icon.Critical)
            connection.close()
            return

        if len(fileContent) == 0:
            showMsgBox(self.tr("The selected attachment is empty (0 bytes)."),
                       title=self.tr("Warning"), icon=QMessageBox.Icon.Warning)
            connection.close()
            return

        if not os.path.exists(self.tempFolder.name):
            QgsMessageLog.logMessage(
                f"Could not access temporary folder: {self.tempFolder.name}",
                'AttachmentManager', level=Qgis.Critical)
            showMsgBox(self.tr("Could not access temporary folder for the file"),
                       title=self.tr("Error"), icon=QMessageBox.Icon.Critical)
            connection.close()
            return

        tempFilePath = os.path.join(self.tempFolder.name, item.text())
        try:
            with open(tempFilePath, 'wb') as f:
                written = f.write(fileContent)
            if written != len(fileContent):
                raise IOError(f"Only {written} of {len(fileContent)} bytes were written.")
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Error writing file to disk: {e}", 'AttachmentManager', level=Qgis.Critical)
            showMsgBox(self.tr("Error writing file to disk."),
                       title=self.tr("Error"), icon=QMessageBox.Icon.Critical)
            connection.close()
            return

        QgsMessageLog.logMessage(
            f"Opening temp file: '{tempFilePath}'", tag="AttachmentManager", level=Qgis.Info)
        connection.close()

        if sys.platform.startswith("win"):
            os.startfile(tempFilePath)
        elif sys.platform == "darwin":
            import subprocess
            subprocess.run(["open", tempFilePath], check=False)
        else:
            if not QDesktopServices.openUrl(QUrl.fromLocalFile(tempFilePath)):
                import subprocess
                subprocess.run(["xdg-open", tempFilePath], check=False)

    def addAttachment(self):
        QgsMessageLog.logMessage("Add attachment called!", tag="AttachmentManager", level=Qgis.Info)
        if len(self.lastActiveLayer.selectedFeatures()) != 1:
            showMsgBox(self.tr("Choose exactly one feature to add attachments to!"),
                       title=self.tr("Warning"), icon=QMessageBox.Icon.Warning)
            return

        fileDialog = QFileDialog()
        fileDialog.setFileMode(_ExistingFile)   # cross-version alias
        if fileDialog.exec():                   # exec() preferred over exec_() in Qt6
            selectedFiles = fileDialog.selectedFiles()
            if len(selectedFiles) != 1:
                showMsgBox(self.tr("Choose exactly one file to attach!"),
                           title=self.tr("Warning"), icon=QMessageBox.Icon.Warning)
                return
            selectedFilePath = selectedFiles[0]
            QgsMessageLog.logMessage(
                f"Selected file to be attached: '{selectedFilePath}'",
                tag="AttachmentManager", level=Qgis.Info)
        else:
            return

        connection = psycopg2.connect(
            database=self.connParams['dbname'], user=self.connParams['user'],
            host=self.connParams['host'], password=self.connParams['password'])
        cursor = connection.cursor()
        attTable = self.connParams['table'][1] + self.tablePostfix
        schema = self.connParams['table'][0]
        fileData = self.getFileData(selectedFilePath)
        sql = (f'INSERT INTO "{schema}"."{attTable}" '
               f'("{self.fieldSetup["id_field"]}", "{self.fieldSetup["name_field"]}", '
               f'"{self.fieldSetup["content_field"]}", "{self.relationalID}") '
               f"VALUES ('{str(uuid.uuid1())}', '{os.path.basename(selectedFilePath)}', "
               f"{Binary(fileData)}, {self.selectedFeatureID});")
        cursor.execute(sql)
        connection.commit()
        connection.close()
        self.loadAttachmentList(self.lastActiveLayer)

    def deleteAttachment(self):
        QgsMessageLog.logMessage("Delete attachment called!", tag="AttachmentManager", level=Qgis.Info)
        item = self.dlg.listAttachment.currentItem()
        if item is None:
            showMsgBox(self.tr("No attachment selected in the list!"),
                       title=self.tr("Warning"), icon=QMessageBox.Icon.Warning)
            return

        connection = psycopg2.connect(
            database=self.connParams['dbname'], user=self.connParams['user'],
            host=self.connParams['host'], password=self.connParams['password'])
        cursor = connection.cursor()
        attTable = self.connParams['table'][1] + self.tablePostfix
        schema = self.connParams['table'][0]
        sql = (f'DELETE FROM "{schema}"."{attTable}" '
               f'WHERE "{self.relationalID}" = {self.selectedFeatureID} '
               f'AND "{self.fieldSetup["name_field"]}" = \'{item.text()}\';')
        QgsMessageLog.logMessage(f"SQL statement: '{sql}'", 'AttachmentManager', level=Qgis.Info)
        cursor.execute(sql)
        connection.commit()
        connection.close()
        self.loadAttachmentList(self.lastActiveLayer)

    def getFileData(self, filePath):
        with open(filePath, 'rb') as f:
            return f.read()

    def setupAttachmentTable(self):
        layer = self.iface.activeLayer()
        text1 = self.tr("Are you sure you want to create an attachment table for layer")
        text2 = self.tr("This will create a new table in the database!")
        if showMsgBox(
                f"{text1} '{layer.name()}'?\n\n{text2}",
                title=self.tr("Confirmation"),
                icon=QMessageBox.Icon.Warning,
                buttons=QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No) == True:
            QgsMessageLog.logMessage(
                "Setup attachment table called!", tag="AttachmentManager", level=Qgis.Info)
            connection = psycopg2.connect(
                database=self.connParams['dbname'], user=self.connParams['user'],
                host=self.connParams['host'], password=self.connParams['password'])
            cursor = connection.cursor()
            attTable = self.connParams['table'][1] + self.tablePostfix
            schema = self.connParams['table'][0]
            sql = (f'CREATE TABLE "{schema}"."{attTable}" ('
                   f'"{self.fieldSetup["id_field"]}" UUID PRIMARY KEY, '
                   f'"{self.fieldSetup["name_field"]}" VARCHAR(255) NOT NULL, '
                   f'"{self.fieldSetup["content_field"]}" BYTEA NOT NULL, '
                   f'"{self.relationalID}" INTEGER NOT NULL);')
            QgsMessageLog.logMessage(f"SQL statement: '{sql}'", 'AttachmentManager', level=Qgis.Info)
            cursor.execute(sql)
            connection.commit()
            connection.close()
            text1 = self.tr("Attachment table")
            text2 = self.tr("created successfully!")
            showMsgBox(
                f"{text1} '{attTable}' {text2}",
                title=self.tr("Info"), icon=QMessageBox.Icon.Information)
            self.onActiveLayerChanged(layer)
            self.dlg.btnSetupAttachments.setEnabled(False)


### === End of AttachmentManager class === ###

def showMsgBox(message, title="Info", icon=QMessageBox.Icon.Information,
               buttons=QMessageBox.StandardButton.Ok):
    msgBox = QMessageBox()
    msgBox.setIcon(icon)
    msgBox.setWindowTitle(title)
    msgBox.setText(message)
    msgBox.setStandardButtons(buttons)
    # exec() is preferred in Qt6; qgis.PyQt keeps exec_() as an alias for Qt5
    result = msgBox.exec()
    return result == QMessageBox.StandardButton.Yes


def parseConnectionString(conn_str: str) -> dict:
    """
    Parse key=value pairs from a QGIS layer source string.
    Dot-connected identifiers like "public"."tablename" are returned as a list.
    """
    def strip_parenthesized_section(s):
        in_single = in_double = False
        for i, ch in enumerate(s):
            if ch == "'" and not in_double:
                in_single = not in_single
            elif ch == '"' and not in_single:
                in_double = not in_double
            elif ch == '(' and not in_single and not in_double:
                return s[:i].rstrip()
        return s.strip()

    def unescape_and_unquote(value):
        v = value.replace(r"\'", "'").replace(r'\"', '"')
        if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
            v = v[1:-1]
        return v

    def split_dotted_identifiers(raw):
        s = raw.strip()
        in_single = in_double = False
        for ch in s:
            if ch == "'" and not in_double:
                in_single = not in_single
            elif ch == '"' and not in_single:
                in_double = not in_double
            elif ch == '.' and not in_single and not in_double:
                break
        else:
            return None

        parts, buf = [], []
        in_single = in_double = False
        for ch in s:
            if ch == "'" and not in_double:
                in_single = not in_single; buf.append(ch)
            elif ch == '"' and not in_single:
                in_double = not in_double; buf.append(ch)
            elif ch == '.' and not in_single and not in_double:
                parts.append(''.join(buf).strip()); buf = []
            else:
                buf.append(ch)
        if buf:
            parts.append(''.join(buf).strip())

        cleaned = []
        for p in parts:
            q = p.replace(r"\'", "'").replace(r'\"', '"')
            if len(q) >= 2 and q[0] == q[-1] and q[0] in ("'", '"'):
                q = q[1:-1]
            cleaned.append(q)
        return cleaned

    def scan_pairs(s):
        i, n, result = 0, len(s), []
        while i < n:
            while i < n and s[i].isspace(): i += 1
            if i >= n: break
            start = i
            while i < n and (s[i].isalnum() or s[i] == '_'): i += 1
            if i == start: break
            key = s[start:i]
            if i >= n or s[i] != '=':
                while i < n and not s[i].isspace(): i += 1
                continue
            i += 1
            in_single = in_double = False
            val_buf = []
            while i < n:
                ch = s[i]
                if ch == "'" and not in_double:
                    in_single = not in_single; val_buf.append(ch); i += 1
                elif ch == '"' and not in_single:
                    in_double = not in_double; val_buf.append(ch); i += 1
                elif ch.isspace() and not in_single and not in_double:
                    break
                else:
                    val_buf.append(ch); i += 1
            result.append((key, ''.join(val_buf).strip()))
        return result

    cleaned = strip_parenthesized_section(conn_str)
    result = {}
    for key, value_str in scan_pairs(cleaned):
        dotted = split_dotted_identifiers(value_str)
        result[key] = dotted if dotted is not None else unescape_and_unquote(value_str)
    return result
